### ISSUE TITLE
[Question]: System has not been booted with systemd as init system. Configuring `molecule.yml` to use pre-built images.

### ISSUE THREAD

**Issue by MaKaNu** [trfore/docker-centos9-systemd#61]
### What happened?

I used your template today to create a rocky9 systemd image.

Well, it turned out I have some issues with accessing systemd and noticed this happens not only to my rocky9 image, it also happens to the other images.

My role which I want is very simple:

- install fail2ban
- call service module to activate and enable fail2ban

The last part is the issue, so I checked inside the containers:

```bash
molecule converge
docker exec -it instance /bin/bash
systemctl status
```

Result:

```bash
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

Any Idea what is going south?

### Relevant log output

```shell

```

### Operating System

archlinux

### Container Manager

Docker

### Container Runtime

containerd, runC

**Comment by trfore** [comment]
So I was curious about the command `bash -c while true; do sleep 10000;done`. It is coming from Molecule's default [`create.yml` playbook](https://github.com/ansible-community/molecule-plugins/blob/980db38a12043e1685dd0e91e9845f1ae684cab1/src/molecule_plugins/docker/playbooks/create.yml#L137). 

I have not run into this issue as I am accustomed to having a more complex `molecule.yml` file that sets `platforms.command` to an **empty string** but allows me to use an environment variable to modify several the `molecule.yml` settings.  For example:

```yaml
platforms:
  - image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2004-systemd}
    name: ${MOLECULE_NAME:-instance}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
```

So it is an interesting design choice by Ansible Molecule's devs, which can easily be prevented by using an empty string. Thanks for bringing this to my attention, I'll update the READMEs.
